\LoadClass[a4paper,cs4size]{ctexart}

% 章节设置
\CTEXsetup[name={第,章},number={\chinese{section}},format+={\heiti \zihao{3}}]{section}
\CTEXsetup[format+={\heiti \zihao{-3}}]{subsection}
\CTEXsetup[format+={\heiti \zihao{4}}]{subsubsection}

% 标题前后间距设置
\CTEXsetup[beforeskip={0em},afterskip={0pt}]{section}
\CTEXsetup[beforeskip={0em},afterskip={0em}]{subsection}
\CTEXsetup[beforeskip={0em},afterskip={0em}]{subsubsection}


